name: Echo Text Workflow

on:
  push:
    branches:
      - main  # or master

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo message
        run: echo "workflow created to echo the text!!."
